baseurl = "https://havron.xyz/blog/"
RelativeURLs = "true"
canonifyURLs = "true"
languageCode = "en-us"
title = "max blog"
theme = "hugo-bootswatch"
[taxonomies]
tag = "tags"
category = "categories"
author = "authors"
# hack by year sorting... ;)
2016 = "2016"
2017 = "2017"
[permalinks]
# Change the permalink format for the 'post' content type.
# This defines how your folder is structured
# post = "/:year/:month/:title/"
post = "/:year/:title/"
copyright = "Unless otherwise specified by the author, this work is licensed under a Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License."
[author]
name = "Samuel Havron"
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
